# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '419a3337-a65d-4315-bb59-6cda224f476a'
    pipeline: '9'
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'neo-ConfuserEx'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CmdLine@2
  inputs:
    script: 'd:\a\1\a\neo-ConfuserEx\Release\bin\Confuser.CLI.exe d:\a\1\s\SafetyKatz.crproj'

- task: CmdLine@2
  inputs:
    script: 'rename d:\a\1\s\SafetyKatz\bin\Release\confused\bin\Release\SafetyKatz.exe d:\a\1\s\SafetyKatz\bin\Release\confused\bin\Release\SafetyKatz_confused.exe'

- task: CopyFiles@2
  inputs:
    Contents: 'SafetyKatz\bin\Release\**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: 'true'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'SafetyKatz'
    publishLocation: 'Container'