version: 0.2

env:
  variables:
    SOLUTION: .\SafetyKatz.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.8

phases:
  build:
    commands:
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" -p:Configuration=Release $env:SOLUTION'
artifacts:
  files:
    - .\SafetyKatz\bin\Release\*
