version: 0.2

phases:
  pre_build:
    commands:
     - New-Item -ItemType Junction -Path C:\Src -Value $Env:CODEBUILD_SRC_DIR
     - cd C:\Src 
  build:
    commands:
     - msbuild /p:TargetFrameworkVersion=v4.0 /p:Configuration=Release
#artifacts:
#  files:
#    - C:\Src\seatbelt\Seatbelt-master\bin\Release\Seatbelt.exe
