version: 0.2

env:
  variables:
    SOLUTION: .\SafetyKatz.sln
    PACKAGE_DIRECTORY: .\packages

phases:
  pre_build:
    commands:
     - nuget.exe restore
  build:
    commands:
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /p:TargetFrameworkVersion=v4.0 /p:Configuration=Release $env:SOLUTION'
artifacts:
  files:
    - .\SafetyKatz\bin\Release\*
