version: 0.2

env:
  variables:
    SOLUTION: .\SafetyKatz.sln
    PACKAGE_DIRECTORY: .\packages

phases:
  pre_build:
    commands:
     - '& nuget.exe restore'
  build:
    commands:
      - '& msbuild /p:TargetFrameworkVersion=v4.0 /p:Configuration=Release $env:SOLUTION'
artifacts:
  files:
    - .\SafetyKatz\bin\Release\*
